services:
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

  migration:
    build: .
    container_name: alembic_migration
    depends_on:
      db:
        condition: service_healthy
    command: ['poetry', 'run', 'alembic', 'upgrade', 'head']
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
